# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wKS8TZ9qD9ngYU1ixj_AQPdIsJVKaD6
"""

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

print("squared:", arr**2)
print("Normalized:", (arr - np.mean(arr)) / np.std(arr))

print("Values > 25:", arr[arr > 25])

print("Reshaped:\n", arr.reshape(-1, 1))